version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: marketplace_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  marketplace-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace_monorepo_app
    restart: always
    ports:
      - "3000:3000" # Mobile Web App (Flutter)
      - "3001:3001" # Admin Panel (React)
      - "3002:3002" # Client Web App (React)
      - "5000:5000" # Backend API & Socket.io Server
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/marketplace_db
      - JWT_SECRET=marketplace_secret_jwt_key_2026
    depends_on:
      - mongodb

volumes:
  mongodb_data:
